//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.ServiceReferenceJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://endpoint.service/", ConfigurationName="ServiceReferenceJava.Decipher")]
    public interface Decipher {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/Decipher/SendFileRequest", ReplyAction="http://endpoint.service/Decipher/SendFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WCFService.ServiceReferenceJava.SendFileResponse SendFile(WCFService.ServiceReferenceJava.SendFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://endpoint.service/Decipher/SendFileRequest", ReplyAction="http://endpoint.service/Decipher/SendFileResponse")]
        System.Threading.Tasks.Task<WCFService.ServiceReferenceJava.SendFileResponse> SendFileAsync(WCFService.ServiceReferenceJava.SendFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFile", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class SendFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg0;
        
        public SendFileRequest() {
        }
        
        public SendFileRequest(string[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFileResponse", WrapperNamespace="http://endpoint.service/", IsWrapped=true)]
    public partial class SendFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://endpoint.service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public SendFileResponse() {
        }
        
        public SendFileResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DecipherChannel : WCFService.ServiceReferenceJava.Decipher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecipherClient : System.ServiceModel.ClientBase<WCFService.ServiceReferenceJava.Decipher>, WCFService.ServiceReferenceJava.Decipher {
        
        public DecipherClient() {
        }
        
        public DecipherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecipherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecipherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecipherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFService.ServiceReferenceJava.SendFileResponse WCFService.ServiceReferenceJava.Decipher.SendFile(WCFService.ServiceReferenceJava.SendFileRequest request) {
            return base.Channel.SendFile(request);
        }
        
        public bool SendFile(string[] arg0) {
            WCFService.ServiceReferenceJava.SendFileRequest inValue = new WCFService.ServiceReferenceJava.SendFileRequest();
            inValue.arg0 = arg0;
            WCFService.ServiceReferenceJava.SendFileResponse retVal = ((WCFService.ServiceReferenceJava.Decipher)(this)).SendFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFService.ServiceReferenceJava.SendFileResponse> WCFService.ServiceReferenceJava.Decipher.SendFileAsync(WCFService.ServiceReferenceJava.SendFileRequest request) {
            return base.Channel.SendFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFService.ServiceReferenceJava.SendFileResponse> SendFileAsync(string[] arg0) {
            WCFService.ServiceReferenceJava.SendFileRequest inValue = new WCFService.ServiceReferenceJava.SendFileRequest();
            inValue.arg0 = arg0;
            return ((WCFService.ServiceReferenceJava.Decipher)(this)).SendFileAsync(inValue);
        }
    }
}
